const SERVER_EVENTS = {
    CHAT_JOIN_RESULT: "CHAT_JOIN_RESULT",
    CHAT_MESSAGE: "CHAT_MESSAGE",
    CHAT_SEND_MESSAGE_RESULT: "CHAT_SEND_MESSAGE_RESULT",
    CHAT_MUTE_RESULT: "CHAT_MUTE_RESULT",
    CHAT_MUTED_USERS: "CHAT_MUTED_USERS",
    CHAT_STATUS: "CHAT_STATUS",
    exception: "exception"
};

const CLIENT_EVENTS = {
    CHAT_JOIN: "CHAT_JOIN",
    CHAT_SEND_MESSAGE: "CHAT_SEND_MESSAGE",
    CHAT_MUTE: "CHAT_MUTE",
};

export { SERVER_EVENTS, CLIENT_EVENTS };
